# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagereceiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='added_by',
            field=models.CharField(default='The Demogorgon', max_length=20),
        ),
    ]
