# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messagereceiver', '0002_message_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagereceiver.Color')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_color',
        ),
        migrations.AddField(
            model_name='queue',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messagereceiver.Message'),
        ),
    ]
